name: C/C++ CI

on:
  # just compile when a 'new version' commit is pushed to master
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  

jobs:
  macos-universal-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install PureData
      run: brew install --cask pd
  
    - name: Install ssl
      run: brew install openssl

    - name: Export lib path
      run: export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/opt/openssl/lib/


    - name: Build Pd
      run: make PDINCLUDEDIR=pure-data/src

    - name: Upload Object
      uses: actions/upload-artifact@v2
      with:
        name: server
        path: server.pd_darwin 
        
    - name: Move server.pd_darwin to test
      run: mv server.pd_darwin test/server.pd_darwin

    - name: Run Test
      run: /Applications/Pd-*.app/Contents/Resources/bin/pd -nogui test/test.pd
    
