name: C/C++ CI

on:
  # just compile when a 'new version' commit is pushed to master
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  

jobs:
  macos-universal-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Clone PureData
      run: git clone https://github.com/puredata/pure-data.git
    
    - name: Install dependencies
      run: brew install openssl@1.1

    - name: Build
      run: c++ -DPD -I "./pure-data/src/" -DCPPHTTPLIB_OPENSSL_SUPPORT -I/usr/local/opt/openssl@1./include -L/usr/local/opt/openssl@1./lib -o src/server.o -c src/server.cpp

