name: C/C++ CI

on:
  # just compile when a 'new version' commit is pushed to master
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  

jobs:
  macos-universal-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    # - name: Install PureData and Dependencies
    #   run: brew install --cask pd && brew unlink openssl && brew link openssl --force && export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/opt/openssl/lib/


    - name: FIND libssl.dylib
      run: which libssl.dylib


    # - name: copy libssl to test
    #   run: cp /usr/local/Cellar/openssl/1.0.2p/lib/libssl.dylib test/libssl.dylib

    # - name: Build server Object
    #   run: make 

    # - name: Upload Object
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: server
    #     path: server.pd_darwin 

    # - name: Upload libssl
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: libssl
    #     path: test/libssl.dylib
        
    # - name: Move server.pd_darwin to test
    #   run: mv server.pd_darwin test/server.pd_darwin

    # - name: Run Test
    #   run: /Applications/Pd-*.app/Contents/Resources/bin/pd -nogui test/test.pd
    
