name: C/C++ CI

on:
  # just compile when a 'new version' commit is pushed to master
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  

jobs:
  macos-universal-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Clone PureData
      run: git clone https://github.com/puredata/pure-data.git
  
    - name: Install ssl
      run: brew install openssl

    - name: Export lib path
      run: export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/opt/openssl/lib/


    - name: Build Pd
      run: make PDINCLUDEDIR=pure-data/src
