name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  macos-universal-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: macos

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build        


